### ISSUE TITLE
Fix title shifting on left arrow hover

### ISSUE THREAD

**Issue by mananshah99** [HarkerDev/bellschedule#8]
This is not a major issue - when a user hovers over the left arrow to shift between weeks, the title text "Bell Schedule" slightly shifts to the right and left.

**Comment by dropbear32** [comment]
This seems to have been fixed a while ago.

**Comment by briankchan** [comment]
I actually still see this: when I hover over the left nav arrow, the title text "Bell Schedule" shifts one pixel to the right; and when I hover over the right arrow, the title shifts one pixel to the left. (Tested on Firefox 61.0.2 and Chrome 69.0.3497.57 beta, both on Windows 10.)

**Comment by bowenyin** [comment]
Yup, the "B" shifts just a little when you hover over the left arrow (Chrome, Mac), but it's so small that you'd have to pay really close attention in order to notice it.

**Comment by dropbear32** [comment]
This only happens in Chrome. In Safari, the c in S**c**hedule moves. I'm thinking this is just how Chrome and Safari handle the arrow's animation. Firefox doesn't have anything strange going on with the title.
